"""Reset migrations

Revision ID: a9f13f11e76d
Revises: 4379989ac528
Create Date: 2024-08-01 00:41:43.280679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9f13f11e76d'
down_revision = '4379989ac528'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_parcels')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_parcels',
    sa.Column('parcel_id', sa.INTEGER(), nullable=False),
    sa.Column('sender_id', sa.INTEGER(), nullable=False),
    sa.Column('tracking_number', sa.VARCHAR(length=20), nullable=False),
    sa.Column('recipient_name', sa.VARCHAR(), nullable=False),
    sa.Column('recipient_address', sa.VARCHAR(), nullable=False),
    sa.Column('recipient_phone', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('weight', sa.DECIMAL(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('current_location', sa.VARCHAR(length=255), nullable=False),
    sa.Column('status', sa.VARCHAR(length=10), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('parcel_id'),
    sa.UniqueConstraint('tracking_number')
    )
    # ### end Alembic commands ###
