"""update users table, add regions

Revision ID: cd6e07ce3d50
Revises: 3e9c55eaad24
Create Date: 2024-08-13 15:28:23.709365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd6e07ce3d50'
down_revision = '3e9c55eaad24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_region', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('operation_areas', sa.String(length=500), nullable=True))
        batch_op.drop_column('region')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('operation_areas')
        batch_op.drop_column('primary_region')

    # ### end Alembic commands ###
